### ISSUE TITLE
Fan pin - faulty ground pin

### ISSUE THREAD

**Issue by indimini** [bdring/Grbl_ESP32_MPCNC_Controller#9]
Hi, 

I just received my board and have grbl software installed on ESP32.  I have power to each of the stepper controllers,  but probing the fan pins w my multi-meter I see 0 V. if I move the gnd probe to the input power Gnd, and keep the + probe on the fan +5V pin, I see 4.95 V.

Is there a config setting I need to change in a .h file to get the fan post to work, or is this a fault in the PCB?

**Comment by bdring** [comment]
The connector should be permanently connected to %V and Gnd. Can you check the solder connection on the back of the board?

![image](https://user-images.githubusercontent.com/189677/80835092-a8790180-8bb7-11ea-8e19-10980161c124.png)

**Comment by indimini** [comment]
Visual inspection doesn't show anything obvious. If I check continuity from the solder joint on the board it still indicates a broken connection.

**Comment by indimini** [comment]
I had no luck with getting gnd on that pin to work by resoldering, so I just soldered a jumper cable from the pin to the input gnd.  Looking at the picture above, it doesn't look like the fan gnd is connected to the input gnd - is that just on a different layer?

**Comment by bdring** [comment]
There are only 2 layer. The bottom reddish layer is mostly a ground plane.  I do limited testing on each board, but every one gets a power supply test. I put power in the input terminal block and measure the output with a meter on those pins.

**Comment by indimini** [comment]
The hard-wired jumper seems like it will work.  There was definitely no voltage across the pins prior to putting in the jumper.  Not a big deal - just thought I'd confirm it wasn't just a software config item before I broke out the soldering iron. :)  The rest of my tests have gone great.  I really appreciate you putting out this board as I was never a fan of Marlin for the CNC and this was a huge move forward.

**Comment by bdring** [comment]
Sometimes those little pins have trouble soldering to a heavy ground plane.
